version: '3.8'

services:
  # PostgreSQL データベース
  db:
    image: postgres:15
    container_name: todoapp_postgres
    environment:
      POSTGRES_DB: todoapp
      POSTGRES_USER: todouser
      POSTGRES_PASSWORD: todopass
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todouser -d todoapp"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Django アプリケーション
  web:
    build: .
    container_name: todoapp_web
    environment:
      - DATABASE_URL=postgresql://todouser:todopass@db:5432/todoapp
      - DJANGO_SETTINGS_MODULE=todoproject.settings
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "
        uv run python manage.py migrate &&
        uv run python manage.py runserver 0.0.0.0:8000
      "

volumes:
  postgres_data: